-- MySQL Script generated by MySQL Workbench
-- Fri Apr  7 16:46:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS test1 DEFAULT CHARACTER SET utf8 ;
USE test1 ;

-- -----------------------------------------------------
-- Table test1.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS test1.`categorie` (
  idcategorie VARCHAR(45) NOT NULL,
  nomcategorie VARCHAR(45) NOT NULL,
  catimage VARCHAR(200) NOT NULL,
  PRIMARY KEY (idcategorie))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table test1.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS test1.`produit` (
  idproduit VARCHAR(45) NOT NULL,
  nomproduit VARCHAR(45) NOT NULL,
  stock INT(5) NOT NULL,
  disponibilite TINYINT(1) NOT NULL,
  idcategorie VARCHAR(45) NOT NULL,
  description LONGTEXT NOT NULL,
  prodimage VARCHAR(200) NOT NULL,
  PRIMARY KEY (idproduit),
  CONSTRAINT idcategorie
    FOREIGN KEY (idcategorie)
    REFERENCES test1.`categorie` (idcategorie)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;